services:
  - type: web
    name: bond-mate-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node -r tsconfig-paths/register dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

