services:
  - type: web
    name: bond-mate-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run render-postbuild
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

