services:
  - type: web
    name: bond-mate-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node -r tsconfig-paths/register dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://amansaroha110:aman123@%23@relationstatus.avjo6eq.mongodb.net/bond_mate_db?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-here-bond-mate-2024

